:construction_worker: feat: 목표 생성 시 progress 기본값 설정 및 progress 로직 수정
magae1/saltyhana_back pull request #79
Opened 2024-12-27 20:49 UTC by hani-i

feat: 목표 생성 시 progress 기본값 설정 및 progress 로직 수정
refactor: 기능 분산을 위한 코드 분리 리팩터링

2024-12-28 03:04 UTC, magae1 requested changes

2024-12-28 03:04 UTC, magae1 commented on src/main/java/com/saltyhana/saltyhanaserver/service/ProgressService.java
> +        System.out.println("가져온 progress 데이터:"+progress.getId());
system.out 보다는 log.debug를 이용. application.properties에서 debug=true로 하면 로그가 보입니다.

2024-12-28 20:56 UTC, hani-i commented on src/main/java/com/saltyhana/saltyhanaserver/listener/GoalEntityListener.java
> +  @Deprecated
엇 코드리뷰를 지금 봤네요 ㅠ

https://jiwon.oopy.io/fe4df7dd-50e5-4a80-bee8-2763967cb186
@Autowired로 의존성 주입할 때 자꾸 에러가 발생해서 찾아보다가 발견한 레퍼런스입니다.
저 레퍼런스 보고 따라했는데, 빼겠습니다 !!

2024-12-28 20:57 UTC, hani-i commented on src/main/java/com/saltyhana/saltyhanaserver/listener/GoalEntityListener.java
> +  private static ProgressService progressService;
이것도 위와 같은 이유로 작성했습니다! Autowired로 주입 시 순환참조 오류가 발생해서 레퍼런스 방법으로 코드 짰습니다.

2024-12-28 20:57 UTC, hani-i commented on src/main/java/com/saltyhana/saltyhanaserver/config/GoalEntityListenerConfig.java
이것도 위 내용과 동일합니다.

2024-12-28 20:59 UTC, hani-i commented on src/main/java/com/saltyhana/saltyhanaserver/service/ProgressService.java
> +    public void initializeProgress(Goal goal){
아! 저건 저 코드가 없으면 GoalEntityListener에서 삽입 로직을 실행하게 되는건데, 그것보다는 service 계층에서 처리하는 게 더 좋아보여서 저렇게 작성했습니다!
저 로직 지우고 GoalEntityListener에서 삽입해주는 게 좋을까요?

2024-12-28 21:00 UTC, hani-i commented on src/main/java/com/saltyhana/saltyhanaserver/service/ProgressService.java
> +        System.out.println("가져온 progress 데이터:"+progress.getId());
좋은 정보 감사합니다~
귀한 중일님 코드리뷰 ,, 미리 봤어야 하는데ㅠ 남겨주셔서 감사해요 !!

2024-12-29 05:19 UTC, magae1 approved these changes

2024-12-29 05:28 UTC, closed without merging